# Required
DATABASE_URL=postgresql://USER:PASSWORD@HOST:5432/DATABASE?sslmode=require
DATA_GO_KR_API_KEY=
ADMIN_API_KEY=replace-with-a-long-random-secret

# Project evidence verification (Naver preferred, Google News RSS fallback)
NAVER_CLIENT_ID=
NAVER_CLIENT_SECRET=
VERIFY_AFTER_COLLECT=true
VERIFY_MAX_PROJECTS=30
VERIFY_NEWS_RESULTS=8
VERIFY_MIN_MATCH_SCORE=58
VERIFY_CONCURRENCY=3
VERIFY_TIMEOUT_SECONDS=20
GOOGLE_NEWS_VERIFY_ENABLED=true
SALES_SIGNAL_MAX_QUERIES=20
SALES_SIGNAL_RESULTS_PER_QUERY=30
SALES_SIGNAL_CONCURRENCY=3
# 비워두면 코드의 선박·전동화 범용 검색어를 사용합니다. 쉼표로 추가 가능.
SALES_SIGNAL_QUERIES=

# Optional channel-specific keys
PUBLIC_DATA_API_KEY=
SHIP_API_KEY=

# Runtime / security
ALLOWED_ORIGINS=https://marinesalesbyminsu.netlify.app,http://localhost:8000
STRICT_STARTUP=false
PORT=8000
LOG_LEVEL=INFO
DB_CONNECT_TIMEOUT_SECONDS=10
COLLECTOR_TIMEOUT_SECONDS=300
API_TIMEOUT_SECONDS=25
API_RETRY_COUNT=3

# Collection scope
DEFAULT_PIPELINE_ALIASES=order_plan,procurement_request,prespec,bid,award,contract,public_data,market_signal,news,public_notice,ship_support,integrated_process
G2B_WINDOW_DAYS=30
BID_LOOKBACK_DAYS=365
CONTRACT_LOOKBACK_DAYS=365
PRESPEC_LOOKBACK_DAYS=365
PROCUREMENT_REQUEST_LOOKBACK_DAYS=365
AWARD_LOOKBACK_DAYS=180
PUBLIC_DATA_LOOKBACK_DAYS=30
ORDER_PLAN_LOOKBACK_MONTHS=6
ORDER_PLAN_FUTURE_MONTHS=24
INTEGRATED_PROCESS_MAX_PROJECTS=40
MAX_PAGES_PER_OPERATION=10
MAX_ITEMS_PER_OPERATION=1000

# Official G2B attachment analysis (PDF/HWP/HWPX/DOCX/XLSX)
DOCUMENT_ANALYSIS_ENABLED=true
DOCUMENT_MAX_PROJECTS_PER_RUN=8
DOCUMENT_MAX_ATTACHMENTS_PER_PROJECT=2
DOCUMENT_MAX_BYTES=15000000
DOCUMENT_MAX_PDF_PAGES=40
DOCUMENT_TIMEOUT_SECONDS=25
DOCUMENT_ALLOWED_HOSTS=g2b.go.kr

# label|URL 형식. 여러 개는 쉼표 또는 줄바꿈으로 구분합니다.
NEWS_RSS_FEEDS=
PUBLIC_NOTICE_RSS_FEEDS=

# Ship APIs / targeting
SHIP_OPERATION_PORT_CODES=
SHIP_SUPPORT_VSSL_NAMES=
SHIP_WATCHLIST_TERMS=3019함,3020함,소방501,소방502,무궁화21호,무궁화41호,한강버스
SHIPYARD_WATCHLIST=금하네이벌텍,동남중공업,삼원중공업,코리아월드써비스,신진조선,대선조선,HJ중공업,에이치제이중공업,대한조선,세진중공업
VESSEL_BUILD_WATCHLIST=대체건조,신조,제작구매,개조,성능개량,전기추진,하이브리드 전기추진,친환경선박,기본설계,실시설계,장비선정위원회
