services:
  - type: web
    name: abb-sdi-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATA_GO_KR_API_KEY
        sync: false
      - key: SHIP_SUPPORT_VSSL_NAMES
        sync: false
      - key: SHIP_OPERATION_PORT_CODES
        sync: false
      - key: INCHEON_PORT_API_KEY
        sync: false
      - key: PORT
        value: 10000
